import 'dart:async';
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:qa_inspector/qa_inspector.dart';
import 'package:qa_inspector/src/report/qa_report_data.dart';
import 'package:qa_inspector/src/report/qa_report_file_sharer.dart';
import 'package:qa_inspector/src/report/qa_report_image_exporter.dart';
import 'package:qa_inspector/src/ui/inspector_shell.dart';

void main() {
  testWidgets('passes generated bytes and filename to sharing', (tester) async {
    final bytes = Uint8List.fromList(<int>[1, 3, 5, 7]);
    final sharer = _FakeSharer();
    final controller = _controller();
    await tester.pumpWidget(_shell(
      controller,
      sharer: sharer,
      exporter: (_, __) async => QaReportExportResult.success(bytes, 'qa_report_20260906_232000.png'),
    ));

    await _export(tester);

    expect(sharer.calls, 1);
    expect(sharer.bytes, same(bytes));
    expect(sharer.filename, 'qa_report_20260906_232000.png');
    expect(sharer.origin, isNot(Rect.zero));
    expect(find.textContaining('PNG report generated'), findsNothing);
    controller.dispose();
  });

  testWidgets('generation failure does not share and shows safe feedback', (tester) async {
    final sharer = _FakeSharer();
    final controller = _controller();
    await tester.pumpWidget(_shell(
      controller,
      sharer: sharer,
      exporter: (_, __) async => QaReportExportResult.failure('The PNG report could not be generated.'),
    ));

    await _export(tester);

    expect(sharer.calls, 0);
    expect(find.text('The PNG report could not be generated.'), findsOneWidget);
    expect(tester.takeException(), isNull);
    controller.dispose();
  });

  testWidgets('share failures do not escape and show safe feedback', (tester) async {
    final controller = _controller();
    await tester.pumpWidget(_shell(
      controller,
      sharer: _FakeSharer(throws: true),
      exporter: (_, __) async => QaReportExportResult.success(Uint8List(1), 'report.png'),
    ));

    await _export(tester);

    expect(find.text('The report could not be shared.'), findsOneWidget);
    expect(tester.takeException(), isNull);
    controller.dispose();
  });

  testWidgets('file preparation failures show safe feedback', (tester) async {
    final controller = _controller();
    await tester.pumpWidget(_shell(
      controller,
      sharer: _FakeSharer(status: QaReportShareStatus.writeFailed),
      exporter: (_, __) async => QaReportExportResult.success(Uint8List(1), 'report.png'),
    ));

    await _export(tester);

    expect(find.text('The report file could not be prepared.'), findsOneWidget);
    expect(tester.takeException(), isNull);
    controller.dispose();
  });

  testWidgets('double export does not start simultaneous operations', (tester) async {
    final completer = Completer<QaReportExportResult>();
    var exports = 0;
    final controller = _controller();
    await tester.pumpWidget(_shell(
      controller,
      sharer: _FakeSharer(),
      exporter: (_, __) {
        exports++;
        return completer.future;
      },
    ));

    await _export(tester, settle: false);
    await tester.tap(find.byKey(const Key('qa-report-actions')));
    await tester.pumpAndSettle();
    final exportItem = tester.widget<PopupMenuItem<Object?>>(find.byKey(const Key('qa-export-png')));
    expect(exportItem.enabled, isFalse);
    await tester.tap(find.byKey(const Key('qa-export-png')));
    await tester.pump();
    expect(exports, 1);
    completer.complete(QaReportExportResult.failure('The PNG report could not be generated.'));
    await tester.pumpAndSettle();
    controller.dispose();
  });

  testWidgets('Copy Report remains independent of PNG sharing', (tester) async {
    String? copied;
    tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(SystemChannels.platform, (call) async {
      if (call.method == 'Clipboard.setData') copied = (call.arguments as Map<Object?, Object?>)['text'] as String?;
      return null;
    });
    final controller = _controller();
    final sharer = _FakeSharer();
    var exports = 0;
    await tester.pumpWidget(_shell(controller, sharer: sharer, exporter: (_, __) async {
      exports++;
      return QaReportExportResult.failure('failure');
    }));

    await tester.tap(find.byKey(const Key('qa-report-actions')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const Key('qa-copy-report')));
    await tester.pumpAndSettle();

    expect(copied, contains('QA REPORT'));
    expect(exports, 0);
    expect(sharer.calls, 0);
    controller.dispose();
  });

  testWidgets('disabled mode does not export or share', (tester) async {
    final controller = QaInspectorController();
    final sharer = _FakeSharer();
    var exports = 0;
    await tester.pumpWidget(_shell(controller, sharer: sharer, exporter: (_, __) async {
      exports++;
      return QaReportExportResult.success(Uint8List(1), 'report.png');
    }));

    await _export(tester);

    expect(exports, 0);
    expect(sharer.calls, 0);
    controller.dispose();
  });
}

QaInspectorController _controller() => QaInspectorController(config: const QaInspectorConfig(enabled: true));

Widget _shell(QaInspectorController controller, {required QaReportSharer sharer, required QaReportExporter exporter}) =>
    MaterialApp(home: InspectorShell(controller: controller, onClose: () {}, reportSharer: sharer, reportExporter: exporter));

Future<void> _export(WidgetTester tester, {bool settle = true}) async {
  await tester.tap(find.byKey(const Key('qa-report-actions')));
  await tester.pumpAndSettle();
  await tester.tap(find.byKey(const Key('qa-export-png')));
  if (settle) await tester.pumpAndSettle(); else await tester.pump();
}

final class _FakeSharer implements QaReportSharer {
  _FakeSharer({this.throws = false, this.status = QaReportShareStatus.shared});

  final bool throws;
  final QaReportShareStatus status;
  int calls = 0;
  Uint8List? bytes;
  String? filename;
  Rect? origin;

  @override
  Future<QaReportShareResult> share({required Uint8List bytes, required String filename, required Rect sharePositionOrigin}) async {
    calls++;
    this.bytes = bytes;
    this.filename = filename;
    origin = sharePositionOrigin;
    if (throws) throw StateError('platform details');
    return QaReportShareResult(status);
  }
}
